### ISSUE TITLE
Inline Lambda IDE doesn't display compressed function code

### ISSUE THREAD

**Issue by iscribble** [Nike-Inc/lambda-zipper#1]
**Issue**:
The resultant output of the lambda-zipper (for a small function) only displays the node-modules package within the inline function editor on the AWS console. Compressing the same files with another utility seems to produce a zipfile that works as expected.

**To Reproduce**:
1. In the AWS console, inspect a function that was compressed using lambda-zipper on the inline-editor. Note functions not rendered.
2. Manually compress the same contents using another utility, such as the OS default.
3. Upload the results directly into the AWS console and press save. Observe the functional code is present.

If you have any trouble reproducing, I could generate an example :)

**Comment by kyeotic** [comment]
Fixed in `0.3.0`
